name: 'Checkout QMK firmware'

inputs:
  version:
    default: '0.22.14'
    type: string
    required: false
  path:
    default: '__qmk__'
    type: string
    required: false

runs:
  using: 'composite'
  steps:

  - name: Checkout qmk_firmware
    uses: actions/checkout@v4
    with:
      path: ${{ inputs.path }}
      repository: vial-kb/vial-qmk
      submodules: recursive
      ref: '2b55e43e5411346a754b81e095b74a042fb48953'

  - name: Setup QMK
    shell: bash
    run: qmk setup --home ${{ inputs.path }} --yes
